pip install flask 
pip install flask_socketio  
pip install cowsay
pip install flask 
pip install SQLAlchemy 
pip install connexion 
pip install Flask-Restless 
pip install Flask-Potion 
pip install flask-restplus 
pip install Flask-Admin 
pip install Flask-Analytics
pip install Flask-Security 
pip install Flask-Login 
pip install Flask-User 
pip install Flask-SQLAlchemy
pip install Flask-WTF 
pip install Flask-Cors
pip install flask-restful
pip install Flask-JWT
pip install pygame
pip install arcade
pip install pygame-menu
pip install pygame-textinput
pip install pyglet
pip install ursina 
pip install django 
pip install beautifulsoup4
pip install selenium
pip install pytest
pip install pytest-django
pip install pytest-cov
pip install pytest-mock
pip install pytest-xdist
pip install pytest-flask
pip install pytest-flask-sqlalchemy
pip install pytest-flask-peewee
pip install pyerror
pip install opencv-python
pip install poetry
pip install flake8
pip install flake8-import-order
pip install flake8-quotes
pip install flake8-print
pip install dlint
pip install pylint
pip install black
pip install beartype
pip install isort
pip install pydocstyle
pip install portray
pip install mypy
pip install requests 
pip install scrapy 
pip install scikit-learn 
pip install authlib
pip install python-oauth2
pip install flask-jwt-extended
pip install tensorflow-gpu 
pip install flask-session
pip install flask-praetorian