pip install flask 
pip install flask_socketio  
pip install cowsay
pip install flask 
pip install SQLAlchemy 
pip install connexion 
pip install Flask-Restless 
pip install Flask-Potion 
pip install flask-restplus 
pip install Flask-Admin 
pip install Flask-Analytics
pip install Flask-Security 
pip install Flask-Login 
pip install Flask-User 
pip install Flask-SQLAlchemy
pip install Flask-WTF 
pip install Flask-Cors
pip install flask-restful
pip install Flask-JWT
pip install pygame
pip install arcade
pip install ursina 
pip install django 
pip install beautifulsoup4
pip install requests 
pip install scrapy 
pip install scikit-learn 
pip install authlib
pip install python-oauth2
pip install flask-jwt-extended
pip install tensorflow-gpu 
pip install flask-session
pip install flask-praetorian