"""New Migration

Revision ID: 58792b22ea8f
Revises: 
Create Date: 2022-04-03 06:03:35.159714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58792b22ea8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_localuser')
    op.drop_table('_googleAuthUser')
    op.drop_table('task_dispatch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_dispatch',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_owner', sa.VARCHAR(), nullable=True),
    sa.Column('activity', sa.VARCHAR(), nullable=False),
    sa.Column('creation_date', sa.DATETIME(), nullable=True),
    sa.Column('due_time', sa.DATETIME(), nullable=True),
    sa.Column('urgency', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['task_owner'], ['_localuser.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_googleAuthUser',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uid', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('profile_pic', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_localuser',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('roles', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
