"""empty message

Revision ID: 9958ed7b1195
Revises: 58792b22ea8f
Create Date: 2022-04-03 06:04:52.882487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9958ed7b1195'
down_revision = '58792b22ea8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_dispatch')
    op.drop_table('_localuser')
    op.drop_table('_googleAuthUser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_googleAuthUser',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uid', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('profile_pic', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_localuser',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('roles', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_dispatch',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_owner', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('starting_date_value', sa.TIME(), nullable=False),
    sa.Column('due_date_value', sa.DATE(), nullable=False),
    sa.Column('due_time_value', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['task_owner'], ['_localuser.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
